/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import javax.swing.JOptionPane;

/**
 *
 * @author juan barraza
 */
public class AddOrganizationOfBranch extends javax.swing.JFrame {

    /**
     * Creates new form AddOrganizationOfBranch
     */
    public AddOrganizationOfBranch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        dniInput = new javax.swing.JTextField();
        nameInput = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        addressInput = new javax.swing.JTextField();
        sexINput = new javax.swing.JTextField();
        yearInput = new javax.swing.JTextField();
        monthInput = new javax.swing.JTextField();
        dayInput = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        typeOrganizationInput = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        numberEmployeesInput = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        nameOrganizationINput = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 128, 128));

        jLabel2.setBackground(new java.awt.Color(0, 128, 128));
        jLabel2.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" Crear Una nueva Organizacion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dniInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dniInputKeyTyped(evt);
            }
        });
        jPanel2.add(dniInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 140, 30));
        jPanel2.add(nameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 140, 30));

        jLabel7.setText("DNI");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel8.setText("Sexo");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        jLabel4.setText("Direccion");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));
        jPanel2.add(addressInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 140, 30));
        jPanel2.add(sexINput, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 140, 30));

        yearInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                yearInputKeyTyped(evt);
            }
        });
        jPanel2.add(yearInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 40, -1));

        monthInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                monthInputKeyTyped(evt);
            }
        });
        jPanel2.add(monthInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 30, -1));

        dayInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dayInputKeyTyped(evt);
            }
        });
        jPanel2.add(dayInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 30, -1));

        jLabel5.setText("Fecha de Nacimiento (dd/mm/yyy)");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel6.setText("/");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jLabel1.setText("/");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel3.setText("(Datos del Representante)");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, 20));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 580, 1));
        jPanel2.add(typeOrganizationInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 140, 30));

        jLabel9.setText("Tipo de organizacion");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        numberEmployeesInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numberEmployeesInputKeyTyped(evt);
            }
        });
        jPanel2.add(numberEmployeesInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 140, 30));

        jLabel10.setText("Numero de empleados");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 60, 20));

        jLabel11.setText("Nombre");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        nameOrganizationINput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameOrganizationINputKeyTyped(evt);
            }
        });
        jPanel2.add(nameOrganizationINput, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 140, 30));

        jLabel12.setText("Nombre");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 580, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dniInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dniInputKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if (caracter < '0' || caracter > '9') {
            evt.consume();
        }

        if (dniInput.getText().length() > 11) {
            evt.consume();
        }
    }//GEN-LAST:event_dniInputKeyTyped

    private void yearInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yearInputKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if (caracter < '0' || caracter > '9') {
            evt.consume();
        }

        if (yearInput.getText().length() > 3) {
            evt.consume();
        }
    }//GEN-LAST:event_yearInputKeyTyped

    private void monthInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_monthInputKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if (caracter < '0' || caracter > '9') {
            evt.consume();
        }

        if (monthInput.getText().length() > 1) {
            evt.consume();
        }
    }//GEN-LAST:event_monthInputKeyTyped

    private void dayInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dayInputKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if (caracter < '0' || caracter > '9') {
            evt.consume();
        }

        if (dayInput.getText().length() > 1) {
            evt.consume();
        }
    }//GEN-LAST:event_dayInputKeyTyped

    private void numberEmployeesInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numberEmployeesInputKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if (caracter < '0' || caracter > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_numberEmployeesInputKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (dniInput.getText().length() != 0
                && nameInput.getText().length() != 0
                && addressInput.getText().length() != 0
                && dayInput.getText().length() != 0
                && dayInput.getText().length() != 0
                && yearInput.getText().length() != 0
                && sexINput.getText().length() != 0
                && typeOrganizationInput.getText().length() != 0
                && numberEmployeesInput.getText().length() != 0
                && nameOrganizationINput.getText().length() != 0) {
            JOptionPane.showMessageDialog(null, "Todo ok");

            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Rellene todo");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void nameOrganizationINputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameOrganizationINputKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_nameOrganizationINputKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddOrganizationOfBranch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddOrganizationOfBranch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddOrganizationOfBranch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddOrganizationOfBranch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddOrganizationOfBranch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressInput;
    private javax.swing.JTextField dayInput;
    private javax.swing.JTextField dniInput;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField monthInput;
    private javax.swing.JTextField nameInput;
    private javax.swing.JTextField nameOrganizationINput;
    private javax.swing.JTextField numberEmployeesInput;
    private javax.swing.JTextField sexINput;
    private javax.swing.JTextField typeOrganizationInput;
    private javax.swing.JTextField yearInput;
    // End of variables declaration//GEN-END:variables
}
